version: '3.8'

services:
  #  https://dev.to/goodidea/how-to-fake-aws-locally-with-localstack-27me
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    hostname: localstack
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - EDGE_PORT=4566
      - SERVICES=s3,sns,sqs,lambda,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  stripe-mock:
    image: stripemock/stripe-mock:latest
    container_name: stripemock
    ports:
      - '12111-12112:12111-12112'
