version: '3.8'

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    ports:
      - "5050:5050"
    volumes:
      - "./build/allure-results:/app/allure-results"
      - "./build/allure-reports:/app/default-reports"

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

  zaproxy:
    image: owasp/zap2docker-stable:latest
    command:
      # Uncomment one of the following lines depending on the desired ZAP mode
      # "zap.sh",
      - "zap-x.sh"
      # "zap-webswing.sh",
      - "-daemon"
      - "-host"
      - "0.0.0.0"
      - "-port"
      - "8082"
      - "-config"
      - "api.disablekey=true"
      - "-config"
      - "api.addrs.addr.name=.*"
      - "-config"
      - "api.addrs.addr.regex=true"
      - "-config"
      - "api.key=d025okl6n7blpkrr0iee6c7hsi"
      # Uncomment the following line to install a specific add-on
      # "-addoninstall FOOXYZ",
      - "-addonupdate"
    ports:
      - "127.0.0.1:8082:8082"
