seleniumhub:
  image: selenium/hub:3.0.0-dubnium
  ports:
    - 4444:4444
  environment:
    - no_proxy=localhost

firefoxnode:
  image: selenium/node-firefox-debug:3.0.0-dubnium
  ports:
    - 5900
  environment:
    - no_proxy=localhost
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome-debug:3.0.0-dubnium
  ports:
    - 5900
  environment:
    - no_proxy=localhost
  links:
    - seleniumhub:hub

functionaltest:
  image: fastertests/javamvn
  links:
    - seleniumhub:localhost
  container_name: tests
  volumes:
    - .:/home
    - ./seluser/.m2:/root/.m2
  command: bash -c "mvn clean test -DsuiteXmlFile=src/test/suite/testng.xml"