version: '3.8'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    container_name: selenoid
    volumes:
      - "./input/selenoid:/etc/selenoid"
      - "./input/selenoid/video:/opt/selenoid/video"
      - "./input/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=PATH_TO_VIDEO_FOLDER
    command:
      - "-conf"
      - "/etc/selenoid/browsers.json"
      - "-video-output-dir"
      - "/opt/selenoid/video"
      - "-log-output-dir"
      - "/opt/selenoid/logs"
      - "-limit"
      - "5" # Change the limit to have more sessions
    ports:
      - "4444:4444"

  selenoid-ui:
    network_mode: bridge
    image: "aerokube/selenoid-ui"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8083:8080"
    networks:
      - selenoid
    command:
      - "--selenoid-uri"
      - "http://selenoid:4444"

networks:
  selenoid:
    name: selenoid
