# Conditional alerts
name: Alerts

on:
  workflow_run:
    workflows: [ Tests ]
    branches: [ master ]
    types: [ completed ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The testing workflow passed'
      - name: Send alert to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
             "text": "Tests Passed (Testing Completed)",
              "attachments": [
                {
                  "pretext": "Testing Finished and Tests Passed",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Passed"
                    }
                  ]
                }
              ]
            }

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The testing workflow failed'
      - name: Send alert to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
             "text": "Tesing Failed (Failed)",
              "attachments": [
                {
                  "pretext": "Testing Failed, please check your tests and re-run",
                  "color": "e32803",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
